# fly.toml app configuration file generated for timeoffapp on 2026-04-29T13:44:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timeoffapp'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'node node_modules/prisma/build/index.js db push --skip-generate'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
